restrict downgrade

diff --git a/.github/workflows/dev.yaml b/.github/workflows/dev.yaml
--- a/.github/workflows/dev.yaml
+++ b/.github/workflows/dev.yaml
@@ -57,6 +57,11 @@ jobs:
             exit 1
           fi
 
+          if [ "$OLD_VERSION" > "$NEW_VERSION" ]; then
+            echo "package.json version can't downgrade"
+            exit 1
+          fi
+
           echo "package.json version bumped."
 
       - name: setup up node
